### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by weishiguan** [ShinanZou/MSAFF#3]
Thank you very much for your contribution, can you provide us with the bone sequence dataset corresponding to the casia_b dataset

**Comment by liguge** [comment]
> Thank you very much for your contribution, can you provide us with the bone sequence dataset corresponding to the casia_b dataset

您好，同学，请问这个问题您解决了吗？我现在也卡在这里了。

**Comment by fffaaaaaa** [comment]
> Thank you very much for your contribution, can you provide us with the bone sequence dataset corresponding to the casia_b dataset

你好，请问你训练过Gait3D或GREW吗，其精度怎么样呢，我的精度很低，不知道是什么原因

**Comment by liguge** [comment]
> Thank you very much for your contribution, can you provide us with the bone sequence dataset corresponding to the casia_b dataset

您好，可以加个好友一起交流一下吗？

**Comment by ShinanZou** [comment]
你能说一下，你的学校和名字吗。我考虑一下吧。其实大部分原因可能在数据处理方面，由于个人工作繁忙，我没有整理好数据处理的代码。



发自我的iPhone


------------------ Original ------------------
From: Chao He ***@***.***&gt;
Date: Thu,Jan 9,2025 7:52 PM
To: ShinanZou/MSAFF ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ShinanZou/MSAFF] dataset (Issue #3)

**Comment by ShinanZou** [comment]
你可以发到我的邮箱。因为GitHub我不经常看的。



发自我的iPhone


------------------ Original ------------------
From: Chao He ***@***.***&gt;
Date: Thu,Jan 9,2025 7:52 PM
To: ShinanZou/MSAFF ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ShinanZou/MSAFF] dataset (Issue #3)





  
Thank you very much for your contribution, can you provide us with the bone sequence dataset corresponding to the casia_b dataset
  
您好，可以加个好友一起交流一下吗？

**Comment by liguge** [comment]
您好， 我是来自北京交通大学的何超，向您请教一些经验问题，不会问一些技术细节，希望得到您的指导。













At 2025-01-09 19:58:11, "ShinanZou" ***@***.***> wrote:

你能说一下，你的学校和名字吗。我考虑一下吧。其实大部分原因可能在数据处理方面，由于个人工作繁忙，我没有整理好数据处理的代码。我的wx号：17853131673



发自我的iPhone


------------------ Original ------------------
From: Chao He ***@***.***&gt;
Date: Thu,Jan 9,2025 7:52 PM
To: ShinanZou/MSAFF ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ShinanZou/MSAFF] dataset (Issue #3)

**Comment by liguge** [comment]
***@***.***  请问这个邮箱您还使用吗？



















在 2025-01-09 19:59:53，"ShinanZou" ***@***.***> 写道：

你可以发到我的邮箱。因为GitHub我不经常看的。



发自我的iPhone


------------------ Original ------------------
From: Chao He ***@***.***&gt;
Date: Thu,Jan 9,2025 7:52 PM
To: ShinanZou/MSAFF ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ShinanZou/MSAFF] dataset (Issue #3)






Thank you very much for your contribution, can you provide us with the bone sequence dataset corresponding to the casia_b dataset

您好，可以加个好友一起交流一下吗？

**Comment by weishiguan** [comment]
***@***.***,联系方式是18235516512。期待您的回复，祝身体健康，万事如意！！！
















在 2025-01-09 19:58:11，"ShinanZou" ***@***.***> 写道：

你能说一下，你的学校和名字吗。我考虑一下吧。其实大部分原因可能在数据处理方面，由于个人工作繁忙，我没有整理好数据处理的代码。



发自我的iPhone


------------------ Original ------------------
From: Chao He ***@***.***&gt;
Date: Thu,Jan 9,2025 7:52 PM
To: ShinanZou/MSAFF ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ShinanZou/MSAFF] dataset (Issue #3)

**Comment by ShinanZou** [comment]
There's already an update note, check it out at ReadMe!
